### ISSUE TITLE
Seafood App Setup - Issue

### ISSUE THREAD

**Issue by AmaduKamara** [AmaduKamara/seafoods-app#21]
# Review Changes made on the issue below ✔️

### GitHub project Link
https://github.com/AmaduKamara/seafoods-app/projects/1

In this project, we are two members-only, @AmaduKamara  and @Debas-31

**Comment by helman101** [comment]
# STATUS: CHANGES REQUIRED ♻️ 🔴 

Hi @AmaduKamara   & @Debas-31   👋, 

Good job so far with this project. 👏 👏👏
You've done well implementing some of the requirements, but there are still some which aren't addressed yet.

## Required Changes ♻️

- [x] You forgot to assing a member of the team to each task, kindly assign task to team member, when a task is assinged it should look like this:
![imagen](https://user-images.githubusercontent.com/60789317/146775546-f755707c-5ffd-4a30-81f6-a056f0b88ea4.png)
    - Kinldy remember to assing the task equaly
![imagen](https://user-images.githubusercontent.com/60789317/146775731-5053e3f9-3532-4834-b3ef-c5b50e75d98e.png)

- [x] You also forgot to delete the default cards, i should see only 15 cards on your project, but currently i can see 18, kindly delete this unnecessary cards:
![imagen](https://user-images.githubusercontent.com/60789317/146783324-65ecdecd-f793-4f90-a88d-f45c6124b8a7.png)



Cheers and Happy coding!👏👏👏

![gif](https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif)

If anything is not 100% clear please leave your questions or comments in the PR thread, we will be glad to help you 😄.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AmaduKamara** [comment]
Oooh, we actually didn't take not of all the assignee thing cause we thought it was just common agreement but it's great we learned how to do all that from the review changes asked. Thanks, Andres, all changes made as requested Sir.

**Comment by dasileker** [comment]
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that my previous colleague didn't see that the link to your Github/project is not there, please add a link.


![kk](https://user-images.githubusercontent.com/61562626/146786877-92fa275f-7d06-482c-8ecc-a2e3f6039300.jpeg)


![nn](https://user-images.githubusercontent.com/61562626/146786974-a20320d3-1e63-4910-8ce0-af9198626b9c.jpeg)




Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Emmyn5600** [comment]
STATUS: APPROVED :+1: 

Hello, @AmaduKamara and @Debas-31  👋🏾 👋🏾 congratulations on implementing all the project requirements.

## Optional suggestions

- Kindly, the link should redirect us to the project setup, use this [one](https://github.com/AmaduKamara/seafoods-app/projects/1)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

**Comment by AmaduKamara** [comment]
Ooh, okay. Thanks so much.

**Comment by AmaduKamara** [comment]
I have updated the link.

**Comment by Emmyn5600** [comment]
Best of luck guys

**Comment by AmaduKamara** [comment]
Thank you, bro.
